// Constantes para los mensajes de ayuda.
export const ADMIN_TITLE = 'Ayuda para administrador.';
export const ADMIN_MESSAGE = 'Como administrador podrás añadir, modificar y eliminar ejercicios, y eliminar tutores y alumnos. Sigue los siguientes pasos:<br><br><ul><li>Pulsa en el avatar que hay en el menú de arriba a la derecha.<br><img src="../Resources/images/help/admin_avatar.png" alt="Imagen del avatar que hay que pulsar para acceder al menú."></li><li>En la página que se abrirá, puedes pulsar las distintas opciones que hay para acceder a las gestiones que puede hacer el administrador. <br><img src="../Resources/images/help/admin_menu.png" alt="Imagen del menú de administrador."></li><li>Si pulsas en el enlace de "Añadir ejercicio" se abrirá un formulario con un campo en el que tendrás que meter el código del ejercicio que quieres añadir y pulsar el botón. <br><img src="../Resources/images/help/add_work.png" alt="Formulario para añadir un nuevo ejercicio."></li><li>Si pulsas en el enlace de "Modificar ejercicio" se abrirá un formulario con un campo en el que tendrás que meter el código del ejercicio que quieres editar y pulsar el botón.<br><img src="../Resources/images/help/select_work.png" alt="Imagen del formulario para elegir el ejercicio a modificar."></li><li>Si el ejercicio existe aparecerá un formulario con las posibles modificaciones que se pueden hacer para este ejercicio en concreto, tendrás que rellenarlas y pulsar el botón.<br><img src="../Resources/images/help/edit_work.png" alt="Imagen del formulario para modificar un ejercicio."></li><li>Si pulsas en el enlace de "Eliminar ejercicio" se abrirá un formulario con un campo en el que tendrás que meter el código del ejercicio que quieres borrar y pulsar el botón.<br><img src="../Resources/images/help/delete_work.png" alt="Imagen del formulario para borrar un ejercicio."></li><li>Si pulsas en el enlace de "Eliminar tutor" se abrirá un formulario con un campo en el que tendrás que meter el código del tutor que quieres borrar y pulsar el botón.<br><img src="../Resources/images/help/delete_tutor.png" alt="Imagen del formulario para borrar un tutor."></li><li>Si pulsas en el enlace de "Eliminar tutor" se abrirá un formulario con un campo en el que tendrás que meter el código del tutor que quieres borrar y pulsar el botón.<br><img src="../Resources/images/help/delete_tutor.png" alt="Imagen del formulario para borrar un tutor."></li></ul>';
export const TUTOR_TITLE = 'Ayuda para tutores.';
export const TUTOR_MESSAGE = '';
export const STUDENT_TITLE = 'Ayuda para alumnos.';
export const STUDENT_MESSAGE = '';
export const VISITOR_TITLE = 'Ayuda para el visitante.';
export const VISITOR_MESSAGE = 'Para hacer los ejercicios o ser tutor, tendrás que registrarte o entrar en tu cuenta. Sigue los siguientes pasos:<br><br><ul><li>Pulsa en el avatar que hay en el menú de arriba a la derecha.<br><img src="../Resources/images/help/avatar.png" alt="Imagen del avatar que hay que pulsar para acceder al login."></li><li>En la página que se abrirá, haz clic en "Regístrate" o introduce tus datos de usuario.<br><img src="../Resources/images/help/new_registration.png" alt="Ubicación del enlace para ir al formulario de registro."></li><li>Si no estás dado de alta, rellena el formulario que se muestra para registrarte.<br><img src="../Resources/images/help/registration_form.png" alt="Formulario para un nuevo registro."></li></ul>';
